<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RpgCompanion.Host</RootNamespace>
      <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.6" />
      <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    </ItemGroup>

    <ItemGroup>
      <Using Include="RpgCompanion.Core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RpgCompanion.Core\RpgCompanion.Core.csproj" />
    </ItemGroup>

</Project>
